# -*- coding: utf-8 -*-
"""Natural FR/DE marketing copy — no AI calques, no robot repetition."""
import json
from pathlib import Path

def set_path(obj, path, value):
    keys = path.split(".")
    cur = obj
    for k in keys[:-1]:
        cur = cur[k]
    cur[keys[-1]] = value

base = Path(__file__).resolve().parents[1] / "locales"

fr = {
  "meta.description": "MontroneDSP développe des plugins audio pour la production électronique — notamment Martello et MartelloX2, synthétiseurs de drums pour Mac, Windows et Linux VST3.",
  "meta.ogDescription": "Synthèse de drums précise, avec le caractère des machines classiques. Martello et MartelloX2 pour Mac VST3/AU, Windows VST3 et Linux VST3.",
  "nav.store": "Boutique",
  "footer.store": "Boutique",
  "home.heroAria": "Présentation du produit",
  "home.martello.lead": "Synthèse de drums précise, avec le caractère des machines classiques.",
  "home.martello.buy": "Acheter le bundle",
  "home.martello.release1": "Améliorations des modèles de drums",
  "home.martello.introTitle": "Conçu pour le groove.",
  "home.martello.introLede": "Martello repose sur des voix de drums synthétisées, avec un résonateur marqué et une forte empreinte de synthèse modale.",
  "home.martello.introBody": "Le son part de l’idée d’objets frappés : corps vibrants, bois, métal, membranes et comportement physique de la percussion. Martello et MartelloX2 sont des synthétiseurs de drums, pas des lecteurs de samples. Concevez kicks, snares, charleys et percussions avec un contrôle immédiat, un modèle par voix et, si besoin, deux moteurs pour un kit complet dans un seul plugin.",
  "home.martello.statement": "Martello n’est pas un pack de samples. C’est un instrument de drums synthétisé, au caractère résonateur et modal : sec, direct, physique.",
  "home.martello.producersAria": "Pour les producers et l’essai",
  "home.martello.producersStatement": "Pour les producers qui veulent des drums qui sonnent joués, accordés, poussés — pas seulement choisis dans un dossier.",
  "home.martello.demoTitle": "Essayez avant d’acheter.",
  "home.martello.demoCopy": "macOS, Windows et Linux. Téléchargements, installation et licence sur la page démo.",
  "home.martello.demoCta": "Télécharger l’essai",
  "home.martello.audioCardTitle": "Enregistrements dry du moteur et démos musicales",
  "home.martello.audioLede": "Voix, modèles et caractères Martello en contexte — kicks, snares, charleys et percussions accordées, directement issus du moteur.",
  "home.martello.validationIndex": "Contrôle qualité",
  "home.martello.validationQuality": "Contrôles qualité",
  "home.martello.validationTitle": "Contrôle qualité",
  "home.martello.validationP1": "Chaque version MontroneDSP passe des contrôles automatisés, une analyse interne du signal, des stress tests et des écoutes musicales réelles.",
  "home.martello.validationP2": "Entre autres : <strong>pluginval correctness level 10</strong>, fréquences d’échantillonnage jusqu’à <strong>192 kHz</strong>, stress d’automation, chargements et déchargements répétés, sessions multi-instances, vérification save/reload, rappel de presets, MIDI, changements rapides de paramètres, rendu offline et contrôle d’intégrité du signal.",
  "home.martello.validationP3": "MartelloX2 est aussi testé sur le comportement dual-engine, le routing multi-output, les sessions lourdes et l’usage réel en projet DAW.",
  "home.martello.devIndex": "Histoire du projet",
  "home.martello.devTitle": "D’où vient Martello.",
  "home.martello.devP1": "L’idée de Martello a pris forme vers 2014, quand j’explorais l’Eurorack, les résonateurs et la synthèse modale. Ces timbres m’attiraient : plus physiques, plus naturels, plus vivants que beaucoup de drums électroniques classiques — des objets frappés, qui vibrent et réagissent dans l’espace.",
  "home.martello.devP2": "Longtemps, j’ai cherché cette sensation avec des samples. Ça n’a jamais vraiment marché pour moi.",
  "home.martello.devP3": "Peu à peu, le chemin s’est clarifié : des drums synthétisés, avec résonateurs et approches physiques, plutôt que des samples seuls.",
  "home.martello.devP4": "C’est devenu le socle de Martello : un instrument de drums immédiat, réactif, vivant. En parallèle je travaillais sur un instrument bien plus complexe ; Martello, lui, s’est naturellement simplifié — clair, rapide, centré sur le son.",
  "home.martello.devP5": "L’interface suit la même logique : pas de sous-menus inutiles, les contrôles principaux sous la main. Martello assume des limites choisies — un point de départ pour construire ses kits, puis les placer dans ses effets, son espace et sa façon de travailler.",
  "home.martello.fieldIndex": "Essai terrain",
  "home.martello.fieldTitle": "Martello face à une vraie pression de PA.",
  "home.martello.fieldVideoAria": "Essai Martello sur système P.A.",
  "home.membrana.lead": "Trois modèles de synthèse — Legacy Elements, Modern Modal et Pipe Engine — réunis autour de la physique de l’exciter, de la géométrie du résonateur et d’un pitch computer dédié.",
  "home.membrana.introTitle": "Frapper, résonner, former.",
  "home.membrana.introLede": "Trois modèles pour membranes, corps et percussions accordées — chacun bâti autour de la physique de l’exciter, de la géométrie du résonateur et d’un pitch computer dédié.",
  "home.membrana.introBody": "Membrana est un synthétiseur physique, pas un lecteur de samples. Legacy Elements pour le caractère membrane classique, Modern Modal pour travailler les corps résonants, Pipe Engine pour les colonnes d’air soufflées et frappées. Puis attaque, résonance et hauteur — dans un seul instrument.",
  "home.membrana.statement": "Un instrument, trois moteurs : du coup membrane vintage au ton de corps modal, jusqu’au souffle du résonateur à tuyau.",
  "home.membrana.bandLegacyVal": "Coup membrane classique",
  "home.membrana.legacyTitle": "Attaque vintage, decay physique.",
  "home.membrana.legacyBody": "Éléments membrane classiques, frappés et soufflés — tension de peau, résonance du corps, attaque brute d’instruments physiques, portés en synthèse jouable. Contour, damping et decay pour drums, peaux et percussions accordées, avec une attitude analogique.",
  "home.membrana.modalTitle": "Formez les modes. Accordez le corps.",
  "home.membrana.modalBody": "Modélisation de résonateur modal pour membranes, plaques et corps vibrants. Obertons, géométrie et damping sous contrôle — du coup sec et serré à l’épanouissement harmonique et aux decays longs qui chantent.",
  "home.membrana.pipeBody": "Physique de tubes et de résonateurs à tuyau pour colonnes d’air soufflées et frappées. Tons d’orgue, flûtes et percussion hybride accordée — pression de souffle, caractère du tube et onde stationnaire d’une colonne réelle, le tout via le même exciter et pitch computer.",
  "home.membrana.audioTitle": "Membrana en contexte.",
  "home.membrana.audioLede": "Nobuo Uematsu — <cite>To Zanarkand</cite> arrangé avec deux voix Membrana et les effets spatiaux Galleria : coup de membrane, ton de corps modal et hall travaillé, en une seule pièce.",
  "home.galleria.lead": "Réverb spectrale de galerie : réflexions lumineuses d’espaces publics et mouvement spatial vivant.",
  "home.galleria.introTitle": "Entrez dans la galerie.",
  "home.galleria.introLede": "Traitement spatial bâti sur des réflexions de hall lumineuses, un delay hybride et un placement 3D piloté par le mouvement.",
  "home.galleria.introBody": "Galleria est une réverb de galerie spectrale — pas un preset de pièce figé. Espace, delay, orbite et texture sur un seul panneau : de l’architecture publique sèche aux queues qui scintillent et se déplacent dans le champ.",
  "home.galleria.statement": "Galleria est un instrument spatial où réflexions, delay et mouvement se composent ensemble — lumineux, fluide, placé avec intention.",
  "home.galleria.bandSpaceVal": "Moteur de réverb + shimmer",
  "home.galleria.bandMotion": "Mouvement",
  "home.galleria.spaceTitle": "Espace public, queue de réverb travaillée.",
  "home.galleria.spaceBody": "Modes classic et spatial, balance early/late indépendante, densité, diffusion et shimmer send dédié. Filtrez l’espace, figez la queue, animez les réflexions — sans perdre la clarté.",
  "home.galleria.motionIndex": "Mouvement 3D",
  "home.galleria.motionTitle": "Placez la source. Bougez le champ.",
  "home.galleria.motionBody": "Placement source X/Y/Z, vitesse et profondeur d’orbite, largeur, doppler, occlusion et air — avec un radar spatial live pour positionner à la volée. Delay et espace suivent la même logique de mouvement, pour une immersion cohérente.",
  "common.getNotified": "Me prévenir",
  "contact.includeTitle": "À indiquer",
  "contact.includeBody": "Indiquez la plateforme (Windows ou Linux), la DAW, la version du plugin si vous la connaissez, et décrivez brièvement le problème. Pour une activation qui coince, ajoutez l’e-mail utilisé au paiement.",
  "contact.responseBody": "Nous répondons en général sous quelques jours ouvrés. Les cas techniques plus complexes peuvent prendre un peu plus de temps.",
  "free.eyebrowTools": "Outils",
  "free.lead": "Quelques outils pratiques pour le quotidien de la prod et du mastering.",
  "free.toolBody": "Convertissez des dossiers entiers vers la fréquence d’échantillonnage voulue, exportez en MP3, et gardez le process simple — pour la prod, l’archive et la livraison.",
  "free.toolLi2": "Conversion de fréquence d’échantillonnage stable",
  "free.toolLi4": "Process simple pour les tâches audio du quotidien",
  "free.ideasBody": "Une petite utilitaire audio vous manque ici ? Écrivez-nous — on peut en tenir compte pour la suite.",
  "dawless.meta.description": "DAWLESS est un projet expérimental MontroneDSP pour les premiers clients : un environnement natif pour instruments et DSP, sans DAW classique.",
  "dawless.meta.ogDescription": "Un environnement natif pour les instruments et le DSP MontroneDSP. Projet expérimental pour les premiers clients.",
  "dawless.lead": "Un environnement natif pour les instruments et le DSP MontroneDSP.",
  "dawless.statusEarly": "Premiers clients",
  "dawless.conceptP1": "DAWLESS est un projet expérimental MontroneDSP pour nos premiers clients. Accès direct à nos moteurs DSP et instruments, dans un environnement natif — sans ouvrir une DAW classique.",
  "dawless.conceptP2": "L’idée : moins de distractions, moins de choix infinis, un parcours plus clair pour produire et enregistrer.",
  "dawless.conceptP3": "Ce n’est pas une DAW de remplacement universelle. C’est un espace de travail où démarrer, composer, séquencer, enregistrer et façonner des idées — puis continuer ailleurs quand le moment vient.",
  "dawless.workflowIntro": "La plupart des DAW proposent tout d’un coup. DAWLESS fait l’inverse : un chemin clair, avec les bons outils déjà en place.",
  "dawless.workflowLi3": "Pas le fouillis typique des DAW",
  "dawless.workflowLi4": "Un parcours clair : créer, séquencer, enregistrer, travailler le son",
  "dawless.workflowOutro": "On vise l’immédiateté d’un workflow type hardware, avec le son et la profondeur de nos instruments — et un export propre vers une chaîne de prod classique, quand vous êtes prêt.",
  "dawless.nativeP1": "DAWLESS tourne autour de nos instruments et DSP — écrits pour l’écosystème MontroneDSP, pas adaptés depuis un host générique.",
  "dawless.nativeP2": "Les moteurs sont les nôtres : processeurs et instruments développés en interne pour cet environnement, sans host tiers ni framework tout fait.",
  "dawless.nativeP3": "L’environnement, c’est le moteur. Sound design, synthèse, processing et séquençage reposent sur la même base que nos plugins — intégrés dès le départ, pas branchés après coup.",
  "dawless.exportP1": "Vous n’êtes pas coincé dans DAWLESS. Quand un projet doit continuer dans une DAW classique — ou partir chez un ingénieur de mix / mastering — des exporters de session vers les DAW les plus utilisées arriveront.",
  "dawless.exportP2": "Le passage d’une session DAWLESS à un mix et un master pro doit rester simple. Commencez ici. Finissez là où votre process l’exige.",
  "demo.lead": "Téléchargez l’essai Martello 7 jours pour macOS, Windows et Linux. Lisez les détails ci-dessous avant d’installer.",
  "demo.aboutBody": "Les essais macOS, Windows et Linux permettent de tester Martello et MartelloX2 dans votre DAW : voix de drums synthétiques, MIDI, stabilité, et le punch machine de la version complète.",
  "demo.aboutLi6": "passez à la version complète à tout moment sur la boutique",
  "demo.downloadsIntro": "Paquets d’essai Martello pour macOS, Windows et Linux. Téléchargez le manuel ci-dessous ou choisissez le lien de votre plateforme. Installer ou utiliser le logiciel vaut acceptation du <a href=\"#martello-eula\">contrat de licence</a> ci-dessous.",
  "demo.macStep3": "Double-cliquez le package d’installation du bundle et suivez l’installeur — ou utilisez l’archive d’installation manuelle fournie.",
  "demo.macStep4": "Ouvrez votre DAW et rescanner les plug-ins si besoin. Les plugins apparaissent sous MontroneDSP.",
  "demo.winStep5": "Ouvrez votre DAW et rescanner les plug-ins si besoin. Le plugin apparaît sous MontroneDSP.",
  "demo.linuxStep5": "Ouvrez votre DAW et rescanner les plug-ins si besoin. Les plugins apparaissent sous MontroneDSP.",
  "demo.eulaTitle": "Contrat de licence utilisateur",
  "demo.eulaIntro": "Martello et MartelloX2 par MontroneDSP. Télécharger un paquet d’essai vaut acceptation de cet accord.",
  "demo.eulaAria": "Contrat de licence Martello, version 1.0.1",
  "demo.eulaMeta": "<strong>Version 1.0.1</strong><br />Dernière mise à jour : 14 juin 2026",
  "privacy.lead": "Les plugins MontroneDSP sont conçus pour limiter la collecte de données. Internet n’est requis que pour l’activation de licence, les contrôles liés, les achats, les téléchargements, le support et le fonctionnement du site — pas pour collecter d’infos sur votre musique, vos sessions, presets, MIDI ou audio.",
  "modi.heroAria": "Présentation Modi archivée",
  "modi.lead": "Ancien concept archivé d’un instrument à résonateurs accordés.",
  "modi.eyebrowLegacy": "Ancien concept",
  "modi.title": "Cette page conserve l’ancienne expérience gratuite centrée sur Modi.",
  "modi.body1": "La page gratuite actuelle se concentre sur des outils pratiques et une mise en page plus simple. Cette archive reste comme référence de l’ancien concept d’instrument à résonateurs.",
  "modi.body2": "On y explorait des tons physiques frappés, des corps résonants accordés, la percussion à maillets, et une synthèse compacte autour du contact, du damping et de l’épanouissement du son.",
}

de = {
  "meta.description": "MontroneDSP entwickelt Audio-Plugins für elektronische Produktion — darunter Martello und MartelloX2, Drum-Synthesizer für Mac, Windows und Linux VST3.",
  "meta.ogDescription": "Präzise Drum-Synthese mit dem Charakter klassischer Machines. Martello und MartelloX2 für Mac VST3/AU, Windows VST3 und Linux VST3.",
  "footer.navAria": "Navigation im Fußbereich",
  "social.title": "Folge uns",
  "products.galleria.short": "Raum",
  "products.membrana.short": "Physik",
  "wheel.hint": "Produkt wählen",
  "home.heroAria": "Produktvorstellung",
  "home.highlightsAria": "Highlights",
  "home.martello.lead": "Präzise Drum-Synthese mit dem Charakter klassischer Machines.",
  "home.martello.release1": "Verbesserungen an den Drum-Modellen",
  "home.martello.introTitle": "Für den Groove gebaut.",
  "home.martello.introLede": "Martello baut auf synthetisierten Drum-Voices mit starkem Resonator- und Modal-Charakter.",
  "home.martello.introBody": "Der Sound kommt von getroffenen Objekten, schwingenden Körpern, Holz, Metall, Membranen und physischem Percussion-Verhalten. Martello und MartelloX2 sind Drum-Synthesizer — keine Sample-Player. Gestalte Kick, Snare, Hi-Hat und Percussion mit direkter Kontrolle, eigenem Modell pro Voice und optional zwei Engines für komplette Kits in einem Plugin.",
  "home.martello.statement": "Martello ist kein Sample-Pack. Es ist ein synthetisiertes Drum-Instrument mit Resonator- und Modal-Charakter: trocken, direkt, physisch.",
  "home.martello.modelTitle": "Jede Voice hat ihre eigene Physik.",
  "home.martello.producersStatement": "Für Producer, die Drums wollen, die sich gespielt anfühlen — gestimmt, mit Druck, mit Charakter. Nicht nur aus einem Ordner gewählt.",
  "home.martello.demoTitle": "Erst testen, dann kaufen.",
  "home.martello.demoCopy": "macOS, Windows und Linux. Downloads, Installation und Lizenz auf der Demo-Seite.",
  "home.martello.demoCta": "Trial laden",
  "home.martello.audioCardTitle": "Dry-Aufnahmen der Engine und musikalische Demos",
  "home.martello.audioLede": "Martello-Voices, Models und Drum-Charaktere im Kontext — synthetische Kicks, Snares, Hi-Hats und gestimmte Percussion direkt aus der Engine.",
  "home.martello.validationIndex": "Qualitätsprüfung",
  "home.martello.validationQuality": "Qualitätschecks",
  "home.martello.validationTitle": "Qualitätsprüfung",
  "home.martello.validationP1": "Jedes MontroneDSP-Release läuft durch automatisierte Checks, interne Signalanalyse, Stress-Tests und echtes musikalisches Hören.",
  "home.martello.validationP2": "Dazu gehören <strong>pluginval correctness level 10</strong>, Sample-Rate-Tests bis <strong>192 kHz</strong>, Automation-Stress, wiederholte Load/Unload-Checks, Multi-Instance-Sessions, Save/Reload-Prüfung, Preset-Recall, MIDI, schnelle Parameterwechsel, Offline-Rendering und Monitoring der Signalintegrität.",
  "home.martello.validationP3": "MartelloX2 wird zusätzlich auf Dual-Engine-Verhalten, Multi-Output-Routing, schwere Sessions und echten DAW-Einsatz geprüft.",
  "home.martello.devIndex": "Entstehungsgeschichte",
  "home.martello.devTitle": "Woher Martello kommt.",
  "home.martello.devP1": "Die Idee zu Martello nahm um 2014 Form an — als ich Eurorack, Resonatoren und Modal-Synthese erkundet habe. Diese Töne wirkten physischer und lebendiger als viele klassische Electronic-Drums: Objekte, die getroffen werden, schwingen und im Raum reagieren.",
  "home.martello.devP2": "Lange habe ich dieses Feeling mit Samples gesucht. Für mich hat es nie wirklich funktioniert.",
  "home.martello.devP3": "Stück für Stück wurde klar: synthetisierte Drums — über Resonatoren und physische Ansätze, nicht nur über Samples.",
  "home.martello.devP4": "Daraus wurde Martello: ein Drum-Instrument, das sofort reagiert — klar, lebendig, ohne Ballast. Parallel arbeitete ich an etwas weit Komplexerem; Martello wurde von selbst direkter, schneller und näher am Sound.",
  "home.martello.devP5": "Das Interface folgt derselben Idee: keine verschachtelten Untermenüs, die wichtigen Regler auf einen Blick. Martello setzt bewusst Limits — als Startpunkt für eigene Kits, die dann in deine Effekte, Räume und Arbeitsweise passen.",
  "home.martello.fieldIndex": "Praxistest",
  "home.martello.fieldTitle": "Martello unter echtem PA-Druck.",
  "home.martello.fieldVideoAria": "Martello im P.A.-Praxistest",
  "home.membrana.lead": "Drei Synthese-Modelle — Legacy Elements, Modern Modal und Pipe Engine — verbunden über Exciter-Physik, Resonator-Geometrie und einen eigenen Pitch Computer.",
  "home.membrana.introTitle": "Anschlagen, schwingen, formen.",
  "home.membrana.introLede": "Drei Modelle für Membranen, Bodies und gestimmte Percussion — jeweils um Exciter-Physik, Resonator-Geometrie und einen Pitch Computer herum gebaut.",
  "home.membrana.introBody": "Membrana ist ein physikalischer Synthesizer, kein Sample-Player. Legacy Elements für klassischen Membrane-Charakter, Modern Modal für resonante Body-Formung, Pipe Engine für geblasene und geschlagene Luftsäulen. Dann Strike, Resonance und Pitch — in einem Instrument.",
  "home.membrana.statement": "Ein Instrument, drei Engines: vom vintage Membrane-Strike über modalen Body-Ton bis zum Atem des Pipe-Resonators.",
  "home.membrana.legacyTitle": "Vintage-Anschlag, physischer Decay.",
  "home.membrana.legacyBody": "Klassische geschlagene und geblasene Membrane-Elemente — Fellspannung, Body-Knock, roher Attack physischer Instrumente, verdichtet zu spielbarer Synthese. Contour, Damping und Decay für Drums, Felle und gestimmte Percussion mit Analog-Charakter.",
  "home.membrana.modalTitle": "Modi formen. Korpus stimmen.",
  "home.membrana.modalBody": "Modale Resonator-Modellierung für Membranen, Platten und schwingende Bodies. Obertöne, Geometrie und Damping präzise steuern — vom trockenen, engen Strike bis zu aufblühendem Oberton und langem, singendem Decay.",
  "home.membrana.pipeBody": "Rohr- und Pipe-Physik für geblasene und geschlagene Luftsäulen. Orgel, Flöte und hybrid gestimmte Percussion — Atemdruck, Bohrungs-Charakter und stehende Welle einer realen Säule, alles über denselben Exciter und Pitch Computer.",
  "home.membrana.audioTitle": "Membrana im Kontext.",
  "home.membrana.audioLede": "Nobuo Uematsu — <cite>To Zanarkand</cite> mit zwei Membrana-Voices und Galleria Spatial FX: Membrane-Strike, modaler Body-Ton und gearbeiteter Hall in einem Stück.",
  "home.galleria.lead": "Spektraler Galerie-Reverb: helle Reflexionen öffentlicher Räume und lebendige Raumbewegung.",
  "home.galleria.introTitle": "Tritt in die Galerie.",
  "home.galleria.introLede": "Raumverarbeitung aus hellen Hall-Reflexionen, Hybrid-Delay und bewegungsgesteuerter 3D-Platzierung.",
  "home.galleria.introBody": "Galleria ist spektraler Galerie-Reverb — kein starres Room-Preset. Space, Delay, Orbit und Texture auf einem Panel: von trockener öffentlicher Architektur bis zu schimmernden Tails, die sich durchs Feld bewegen.",
  "home.galleria.statement": "Galleria ist ein Spatial-Instrument, in dem Reflexionen, Delay und Bewegung zusammenwirken — hell, weich, bewusst platziert.",
  "home.galleria.spaceTitle": "Öffentlicher Raum, gearbeiteter Reverb-Tail.",
  "home.galleria.spaceBody": "Classic- und Spatial-Reverb mit unabhängiger Early/Late-Balance, Density, Diffusion und eigenem Shimmer-Send. Raum filtern, Tail einfrieren, Reflexionen bewegen — ohne Klarheit zu verlieren.",
  "home.galleria.motionTitle": "Quelle platzieren. Feld bewegen.",
  "home.galleria.motionBody": "Source X/Y/Z, Orbit-Rate und -Tiefe, Width, Doppler, Occlusion und Air — mit Live-Spatial-Radar für Positioning in Echtzeit. Delay und Space folgen derselben Bewegungslogik, damit das Raumgefühl zusammenhält.",
  "common.getNotified": "Benachrichtigen",
  "contact.lead": "Fragen zu Martello, Lizenz, Installation oder Bestellung? Schreib uns — wir melden uns.",
  "contact.includeBody": "Bitte Plattform (Windows oder Linux), DAW, Plugin-Version falls bekannt und eine kurze Beschreibung. Bei Aktivierungsproblemen die Checkout-E-Mail mit angeben.",
  "contact.responseBody": "In der Regel antworten wir innerhalb weniger Werktage. Kniffligere Technikfälle können länger dauern.",
  "free.eyebrowFree": "Kostenlos",
  "free.eyebrowTools": "Tools",
  "free.title": "Einfache, kostenlose Utilities für die Audioproduktion.",
  "free.lead": "Ein kleines Set praktischer Tools für den Alltag in Produktion und Mastering.",
  "free.toolBody": "Ganze Ordner auf die gewünschte Sample Rate bringen, MP3s exportieren, den Ablauf klar halten — für Produktion, Archiv und Abgabe.",
  "free.toolLi3": "MP3-Encoding zum Teilen und zur Abgabe",
  "free.ideasBody": "Dir fehlt hier eine kleine Audio-Utility? Schreib uns — wir können das für den nächsten Stand mitdenken.",
  "dawless.meta.description": "DAWLESS ist ein experimentelles MontroneDSP-Projekt für Frühkunden: eine eigene Umgebung für Instrumente und DSP, ohne klassische DAW.",
  "dawless.meta.ogDescription": "Eigene Umgebung für MontroneDSP-Instrumente und DSP. Experimentelles Projekt für Frühkunden.",
  "dawless.lead": "Eigene Umgebung für MontroneDSP-Instrumente und DSP.",
  "dawless.conceptP1": "DAWLESS ist ein experimentelles Projekt für unsere ersten Kunden. Direkter Zugang zu unseren DSP-Engines und Instrumenten in einer nativen Umgebung — ohne klassische DAW.",
  "dawless.conceptP2": "Weniger Ablenkung, weniger endlose Optionen, ein klarerer Weg zu Produktion und Aufnahme.",
  "dawless.conceptP3": "Kein Ersatz für jede DAW. Ein Arbeitsraum zum Starten, Komponieren, Sequenzieren, Aufnehmen und Formen — und später weiterführen, wenn der Zeitpunkt stimmt.",
  "dawless.workflowIntro": "Die meisten DAWs bieten alles auf einmal. DAWLESS macht das Gegenteil: klarer Pfad, die wichtigen Tools schon an Ort und Stelle.",
  "dawless.workflowLi3": "Kein typisches DAW-Chaos",
  "dawless.workflowLi4": "Klarer Weg: Erstellen, Sequenzieren, Aufnehmen, Sound formen",
  "dawless.workflowOutro": "Unmittelbarkeit und Fokus wie bei Hardware-DAWless — mit dem Sound und der Tiefe unserer Instrumente, und mit Export in eine klassische Prod-Pipeline, wenn du soweit bist.",
  "dawless.nativeP1": "DAWLESS baut auf unseren Instrumenten und DSP — geschrieben fürs MontroneDSP-Ökosystem, nicht aus einem generischen Host übernommen.",
  "dawless.nativeP2": "Die Engines sind eigen: Prozessoren und Instrumente intern für diese Umgebung, ohne Drittanbieter-Host und ohne Fertig-Framework.",
  "dawless.nativeP3": "Die Umgebung ist die Engine. Sound Design, Synthese, Processing und Sequenzierung laufen auf derselben Basis wie unsere Plugins — von Anfang an, nicht nachgeladen.",
  "dawless.exportP1": "Du bleibst nicht in DAWLESS stecken. Wenn ein Projekt in einer klassischen DAW weitergeht — oder an Mix-/Mastering-Engineers geht — kommen Session-Exporter für die gängigsten DAWs.",
  "dawless.exportP2": "Der Schritt von einer DAWLESS-Session in Mix und Master soll direkt und ruhig sein. Hier starten. Dort fertigmachen, wo dein Prozess es braucht.",
  "demo.lead": "Lade die 7-Tage-Martello-Trial für macOS, Windows und Linux. Details unten lesen, bevor du installierst.",
  "demo.aboutBody": "Die Trials für macOS, Windows und Linux lassen dich Martello und MartelloX2 in der DAW prüfen: synthetische Drum-Voices, MIDI, Stabilität und den Machine-Punch der Vollversion.",
  "demo.aboutLi6": "Vollversion jederzeit im Store kaufen",
  "demo.downloadsIntro": "Martello-Trial-Pakete für macOS, Windows und Linux. Manual unten laden oder den Link für deine Plattform nutzen. Installation oder Nutzung setzt die Zustimmung zur unten stehenden <a href=\"#martello-eula\">Lizenzvereinbarung</a> voraus.",
  "demo.eulaTitle": "Endnutzer-Lizenzvereinbarung",
  "demo.eulaIntro": "Martello und MartelloX2 von MontroneDSP. Der Download eines Trial-Pakets gilt als Annahme dieser Vereinbarung.",
  "demo.eulaAria": "Martello-Lizenzvereinbarung, Version 1.0.1",
  "demo.eulaMeta": "<strong>Version 1.0.1</strong><br />Zuletzt aktualisiert: 14. Juni 2026",
  "privacy.lead": "MontroneDSP-Plugins sind auf minimale Datenerhebung ausgelegt. Internet braucht es nur für Lizenzaktivierung, lizenzbezogene Checks, Käufe, Downloads, Support und den Website-Betrieb — nicht, um Infos über deine Musik, Sessions, Presets, MIDI oder Audio zu sammeln.",
  "modi.heroAria": "Archivierte Modi-Vorstellung",
  "modi.lead": "Archiviertes Konzept eines gestimmten Resonator-Instruments.",
  "modi.cta": "Zur aktuellen Seite mit den Free Tools",
  "modi.title": "Hier bleibt die frühere, Modi-zentrierte Free-Seite erhalten.",
  "modi.body1": "Die aktuelle Free-Seite setzt auf praktische Tools und ein schlankeres Layout. Diese Archivseite bleibt als Referenz zum früheren Resonator-Konzept.",
  "modi.body2": "Es ging um angeschlagene physische Töne, gestimmte Resonanzkörper, Mallet-Percussion und kompakte Synthese um Kontakt, Dämpfung und das Aufblühen des Sounds.",
}

for name, fixes in [("fr.json", fr), ("de.json", de)]:
    path = base / name
    data = json.loads(path.read_text(encoding="utf-8"))
    for p, v in fixes.items():
        set_path(data, p, v)
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"{name}: {len(fixes)} fixes")

# leftover smell checks
smells = {
  "fr.json": ["focalisé", "concentré", "immersif", "écrits à la main", "Validation de release", "rescassez", "Last updated", "early customers", "Hero produit", "une pipeline"],
  "de.json": ["fokussiert", "handwritten", "Release Validation", "Quality Checks", "Dev Story", "Field Test", "immersiv", "Last updated", "Produkt-Hero"],
}
for name, bad in smells.items():
    text = (base / name).read_text(encoding="utf-8")
    hits = [b for b in bad if b in text]
    print(f"{name} leftover: {hits or 'none'}")
