# -*- coding: utf-8 -*-
"""Natural JA / zh-CN marketing copy — native product voice, not literal AI."""
import json
from pathlib import Path

def set_path(obj, path, value):
    keys = path.split(".")
    cur = obj
    for k in keys[:-1]:
        cur = cur[k]
    cur[keys[-1]] = value

base = Path(__file__).resolve().parents[1] / "locales"

ja = {
  "meta.title": "MontroneDSP  -  ドラムシンセと実験的サウンドのためのオーディオプラグイン",
  "meta.description": "MontroneDSPは電子音楽向けのオーディオプラグインを開発。MartelloとMartelloX2は、Mac・Windows・Linux対応のVST3ドラムシンセです。",
  "meta.ogDescription": "クラシックなドラムマシンの気配を残した、キレのあるドラムシンセ。MartelloとMartelloX2は Mac VST3/AU、Windows VST3、Linux VST3 対応です。",
  "home.heroAria": "製品紹介",
  "home.highlightsAria": "主な特徴",
  "home.martello.lead": "クラシックなドラムマシンの気配を残した、キレのあるドラムシンセ。",
  "home.martello.introTitle": "グルーヴのために生まれた。",
  "home.martello.introLede": "Martelloの核は、レゾネーターとモーダルシンセの影響が強い、合成のドラムボイスです。",
  "home.martello.introBody": "サウンドの発想は、叩かれた物体、振動するボディ、木、金属、膜、そして生のパーカッションの振る舞い。MartelloとMartelloX2はサンプラーではなくドラムシンセです。キック、スネア、ハット、パーカッションを、すぐ触れる操作感、ボイスごとのモデル選択、必要ならデュアルエンジンで、ひとつのプラグインにフルキットまで組めます。",
  "home.martello.statement": "Martelloはサンプルパックではありません。レゾネーターとモーダルの性格を持った合成ドラム楽器——ドライで、ダイレクトで、物理的。",
  "home.martello.modelTitle": "ボイスごとに、物理を選ぶ。",
  "home.martello.producersStatement": "フォルダから選ぶだけのドラムではなく、弾いて、チューニングして、追い込んで、形を作るドラムが欲しい人のために。",
  "home.martello.demoTitle": "買う前に、まず試す。",
  "home.martello.demoCopy": "macOS、Windows、Linux。ダウンロード、インストール手順、ライセンスはデモページに。",
  "home.martello.demoCta": "体験版をダウンロード",
  "home.martello.audioCardTitle": "エンジンのドライ録音と楽曲デモ",
  "home.martello.audioLede": "Martelloのボイス、モデル、ドラムの性格を実際の音で——エンジンから出るキック、スネア、ハット、チューンド・パーカッション。",
  "home.martello.validationIndex": "品質検証",
  "home.martello.validationTitle": "品質検証",
  "home.martello.validationP1": "MontroneDSPの各リリースは、自動テスト、内部の信号解析、ストレステスト、そして実際の楽曲での試聴を通過しています。",
  "home.martello.validationP2": "内容は<strong>pluginval correctness level 10</strong>、<strong>192 kHz</strong>までのサンプルレート、オートメーションの負荷テスト、反復ロード／アンロード、マルチインスタンス、保存／再読み込み、プリセットリコール、MIDI、急なパラメータ変更、オフラインレンダリング、信号の整合性モニタリングなどです。",
  "home.martello.validationP3": "MartelloX2はさらに、デュアルエンジン、マルチアウト、重いセッション、実DAWプロジェクトでの使い勝手も確認しています。",
  "home.martello.devIndex": "開発の経緯",
  "home.martello.devTitle": "Martelloはどう始まったか。",
  "home.martello.devP1": "Martelloの種は2014年頃、Eurorack、レゾネーター、モーダルシンセを触っていたころに芽生えました。従来の電子ドラムより、物理的で、自然で、生きている——叩かれ、震え、空間で反応する物体の感触に惹かれていました。",
  "home.martello.devP2": "長いあいだサンプルでその感触を追いかけましたが、自分には届きませんでした。",
  "home.martello.devP3": "やがて道ははっきりしました。サンプルだけに頼らず、レゾネーターと物理的なアプローチでドラムを合成する、という方向です。",
  "home.martello.devP4": "それがMartelloの土台になりました。すぐ反応し、生きているドラム楽器。並行してもっと複雑な楽器も作っていましたが、Martelloは自然と、よりストレートで、わかりやすく、すぐ使え、サウンド中心のものになりました。",
  "home.martello.devP5": "UIも同じです。入り組んだサブメニューはなく、主な操作は目の前にあります。Martelloはあえて制約を置き、自分のキットを組み、自分のエフェクトや空間、いつもの作業の流れに乗せるための出発点にしています。",
  "home.martello.fieldIndex": "実機テスト",
  "home.martello.fieldTitle": "本物のPAの前で、Martello。",
  "home.martello.fieldVideoAria": "MartelloのP.A.実機テスト映像",
  "home.membrana.lead": "Legacy Elements、Modern Modal、Pipe Engine——3つのモデルを、エキサイターの物理、レゾネーターの形状、専用のピッチコンピューターでつなぐ。",
  "home.membrana.introTitle": "叩く、響かせる、形にする。",
  "home.membrana.introLede": "膜、ボディ、チューンドパーカッション向けの3モデル。いずれもエキサイターの物理、レゾネーターの形状、専用ピッチコンピューターを軸にしています。",
  "home.membrana.introBody": "Membranaはサンプラーではなく物理モデリングシンセです。膜のクラシックな質感はLegacy Elements、共振ボディはModern Modal、息を吹き／叩く気柱はPipe Engine。打撃、共振、ピッチを、ひとつの楽器で扱えます。",
  "home.membrana.statement": "ひとつの楽器、3つのエンジン——ヴィンテージな膜の打撃から、モーダルなボディトーン、パイプの息まで。",
  "home.membrana.bandLegacyVal": "クラシックな膜の打撃",
  "home.membrana.legacyTitle": "ヴィンテージの打撃、物理的な減衰。",
  "home.membrana.legacyBody": "クラシックな打撃・吹奏の膜——皮の張力、ボディのノック、生楽器の生々しいアタックを、演奏できるシンセに落とし込みます。ドラム、皮、チューンドパーカッションに、アナログ時代の気配で輪郭、ダンピング、ディケイを与えられます。",
  "home.membrana.modalTitle": "モードを形にし、ボディをチューニングする。",
  "home.membrana.modalBody": "膜、プレート、振動ボディ向けのモーダルレゾネーター。倍音、形状、ダンピングを精密に——ドライで鋭い打撃から、広がるハーモニクス、長く歌うディケイまで。",
  "home.membrana.pipeTitle": "ボア、息、気柱の共鳴。",
  "home.membrana.pipeBody": "吹奏・打撃の気柱のためのチューブ／パイプ物理。オルガン、フルート、ハイブリッドなピッチパーカッション——息圧、ボアの性格、物理気柱の定在波を、同じエキサイターとピッチコンピューターで動かします。",
  "home.membrana.audioTitle": "Membranaの音を聴く。",
  "home.membrana.audioLede": "Nobuo Uematsu — <cite>To Zanarkand</cite>を、2つのMembranaボイスとGalleriaの空間FXで。膜の打撃、モーダルなボディトーン、つくり込んだホールを一曲に。",
  "home.galleria.lead": "明るい公共空間の反射と、生きた空間の動きを持つスペクトラル・ギャラリーリバーブ。",
  "home.galleria.introTitle": "ギャラリーを歩く。",
  "home.galleria.introLede": "明るいホール反射、ハイブリッドディレイ、動きで動かす3D配置を軸にした空間処理。",
  "home.galleria.introBody": "Galleriaは固定のルームプリセットではなく、ギャラリーのようなスペクトラルリバーブです。空間、ディレイ、オービット、テクスチャを一枚のパネルで——乾いた公共建築から、フィールドを動くきらめくテイルまで。",
  "home.galleria.statement": "Galleriaは、反射・ディレイ・動きをひと続きで組む空間楽器——明るく、滑らかで、意図して置く。",
  "home.galleria.spaceTitle": "公共空間、つくり込んだテイル。",
  "home.galleria.spaceBody": "クラシックと空間リバーブ、独立したアーリー／レイト、密度、ディフュージョン、専用シマーセンド。空間をフィルターし、テイルをフリーズし、明瞭さを保ったまま反射を動かせます。",
  "home.galleria.motionTitle": "ソースを置き、フィールドを動かす。",
  "home.galleria.motionBody": "ソースのX/Y/Z、オービットの速さと思み、幅、ドップラー、オクルージョン、エア——ライブの空間レーダー付き。ディレイと空間は同じ動きのロジックに沿い、まとまりのある没入感を保ちます。",
  "common.getNotified": "リリースを知らせる",
  "contact.lead": "Martello、ライセンス、インストール、ご注文について——メールでどうぞ。折り返しご連絡します。",
  "contact.includeBody": "OS（WindowsまたはLinux）、DAW名、分かる場合はプラグインのバージョン、内容の簡単な説明をお書きください。アクティベーションの不具合なら、購入時のメールアドレスも添えてください。",
  "contact.responseBody": "通常は数営業日以内にご返信します。複雑な技術案件は、調査のためもう少しお時間をいただくことがあります。",
  "free.lead": "日常の制作やマスタリングにすっと入る、小さな実用ツールです。",
  "free.toolBody": "フォルダごと任意のサンプルレートへ変換し、MP3も書き出せます。制作・アーカイブ・納品を、余計な手間なく。",
  "free.ideasBody": "ここに欲しい小さなオーディオツールがあれば、ぜひ。次のリリースの参考にします。",
  "dawless.meta.description": "DAWLESSは初期ユーザー向けの実験プロジェクト。従来のDAWなしで、楽器とDSPに集中できるネイティブ環境です。",
  "dawless.meta.ogDescription": "MontroneDSPの楽器とDSPのためのネイティブ環境。初期ユーザー向けの実験プロジェクト。",
  "dawless.lead": "MontroneDSPの楽器とDSPのためのネイティブ環境。",
  "dawless.statusEarly": "初期ユーザー向け",
  "dawless.conceptP1": "DAWLESSは、最初のお客様のための実験プロジェクトです。自社のDSPエンジンと楽器に、ネイティブ環境から直接触れられます——従来のDAWを開く必要はありません。",
  "dawless.conceptP2": "目指すのは、気が散りにくく、選択肢が暴れない、制作と録音の道筋がはっきりしたワークステーションです。",
  "dawless.conceptP3": "あらゆるDAWの置き換えではありません。作曲、シーケンス、録音、音色づくりまでをスムーズに進め、必要なときに次の工程へ渡せる制作空間です。",
  "dawless.workflowIntro": "多くの制作環境は、すべてを一度に差し出します。DAWLESSはその逆——進む道がはっきりしていて、必要な道具はすでに揃っています。",
  "dawless.workflowLi3": "汎用DAWの雑多なUIなし",
  "dawless.workflowLi4": "創作・シーケンス・録音・音色づくりのはっきりした流れ",
  "dawless.workflowOutro": "ハードウェア寄りのDAWlessの即時性と集中を、自社楽器とDSPの音の深さとつなぎ、準備ができたら従来のプロダクションへ書き出せるようにします。",
  "dawless.nativeP1": "DAWLESSは自社の楽器とDSPが中心——汎用ホストからの移植ではなく、MontroneDSPのために書いたものです。",
  "dawless.nativeP2": "エンジンは自社開発。この環境用のプロセッサと楽器で、サードパーティのホストや既成フレームワークには依存しません。",
  "dawless.nativeP3": "環境そのものがエンジンです。サウンドデザイン、シンセ、処理、シーケンスは、プラグインと同じ基盤の上で最初から一体になっています。",
  "dawless.exportP1": "DAWLESSに閉じ込められません。従来のDAWで続けたいとき——あるいはミックス／マスタリングのエンジニアに渡したいとき——主要DAW向けのセッション書き出しを用意する予定です。",
  "dawless.exportP2": "DAWLESSのセッションから本格的なミックス／マスターへは、まっすぐで負担の少ない流れにします。ここから始めて、プロセスが求める場所で仕上げてください。",
  "demo.lead": "macOS・Windows・Linux向けのMartello 7日間トライアル。インストール前に、以下をご確認ください。",
  "demo.aboutBody": "トライアルでは、お使いのDAWでMartelloとMartelloX2を試せます。合成ドラム、MIDI、安定性、フル版と同じマシンのパンチを確認できます。",
  "demo.aboutLi6": "ストアからいつでもフル版へ",
  "demo.downloadsIntro": "macOS・Windows・Linux向けのトライアルパッケージです。下のマニュアル、または各OSのリンクから。インストール／使用には下記の<a href=\"#martello-eula\">エンドユーザーライセンス契約</a>への同意が必要です。",
  "demo.eulaMeta": "<strong>Version 1.0.1</strong><br />最終更新：2026年6月14日",
  "privacy.lead": "MontroneDSPのプラグインは、データ収集を最小限に抑える設計です。ネット接続が必要になるのは、ライセンスの有効化と関連確認、購入、ダウンロード、サポート、サイト運用に限られます——音楽やセッション、プリセット、MIDI、オーディオを集めるためではありません。",
  "modi.heroAria": "アーカイブされた Modi 紹介",
  "modi.lead": "調律されたレゾネーター楽器の、旧コンセプトのアーカイブ。",
  "modi.title": "無料ページの、初期の Modi 中心版を残しています。",
  "modi.body1": "いまの無料ページは実用ツールとシンプルなレイアウトです。このアーカイブは、以前のレゾネーター楽器コンセプトの参照用です。",
  "modi.body2": "打撃の物理的な音色、調律された共鳴体、マレット打楽器、接触・ダンピング・音の広がりを軸にしたコンパクトなシンセを探っていました。",
}

zh = {
  "meta.title": "MontroneDSP  -  鼓合成与实验声音的音频插件",
  "meta.description": "MontroneDSP 开发电子音乐用音频插件，包括 Martello 与 MartelloX2 鼓合成器，支持 Mac、Windows 与 Linux VST3。",
  "meta.ogDescription": "带着经典鼓机气质的精准鼓合成。Martello 与 MartelloX2 支持 Mac VST3/AU、Windows VST3 与 Linux VST3。",
  "home.martello.lead": "带着经典鼓机气质的精准鼓合成。",
  "home.martello.introTitle": "为律动而生。",
  "home.martello.introLede": "Martello 以合成鼓声部为核心，深受谐振器与模态合成影响。",
  "home.martello.introBody": "声音的灵感来自击打物体、振动体、木材、金属、膜片，以及真实打击乐的物理反应。Martello 与 MartelloX2 是鼓合成器，不是采样器。用即时操控、每声部独立模型，以及可选的双引擎路由，做底鼓、军鼓、踩镲与打击乐——一个插件里就能组完整套。",
  "home.martello.statement": "Martello 不是采样包。它是带有谐振器与模态气质的合成鼓乐器：干、直接、有物理感。",
  "home.martello.modelTitle": "每个声部，自选物理。",
  "home.martello.producersStatement": "给想要鼓声可弹、可调、可推、可塑的制作人——不是从文件夹里点选。",
  "home.martello.demoTitle": "先试再买。",
  "home.martello.demoCopy": "支持 macOS、Windows 与 Linux。下载、安装说明与许可协议见试用页。",
  "home.martello.audioCardTitle": "引擎干声录音与音乐小样",
  "home.martello.audioLede": "结合实际编曲听 Martello 的声部、模型与鼓性格——引擎生成的底鼓、军鼓、踩镲与调谐打击乐。",
  "home.martello.validationIndex": "质量验证",
  "home.martello.validationTitle": "质量验证",
  "home.martello.validationP1": "每一版 MontroneDSP 发布都会经过自动测试、内部信号分析、压力测试，以及真人音乐试听。",
  "home.martello.validationP2": "包括 <strong>pluginval correctness level 10</strong>、最高 <strong>192 kHz</strong> 采样率、自动化压力、反复加载／卸载、多实例会话、保存／重载、预设召回、MIDI、快速改参、离线渲染，以及信号完整性监测。",
  "home.martello.validationP3": "MartelloX2 还会额外检查双引擎、多输出路由、高负载会话，以及真实 DAW 工程里的可用性。",
  "home.martello.devIndex": "开发故事",
  "home.martello.devTitle": "Martello 从何而来。",
  "home.martello.devP1": "Martello 的想法大约在 2014 年成形。那时我在玩 Eurorack、谐振器与模态合成。那些音色比许多传统电子鼓更有物理感、更活——像物体被击打、振动，并在空间里回应。",
  "home.martello.devP2": "很久我都想用采样抓住那种感觉，但始终不对。",
  "home.martello.devP3": "渐渐地，方向清楚了：用谐振器与物理方法做合成鼓，而不是只靠采样。",
  "home.martello.devP4": "那条路成了 Martello 的根基：即时、灵敏、有生命力的鼓乐器。同时我还在做一件复杂得多的乐器；Martello 则自然变得更直接、更好懂、更快上手，也更围绕声音本身。",
  "home.martello.devP5": "界面也一样：没有绕人的子菜单，主控一眼可见。Martello 故意设限——给你一个起点去设计自己的鼓组，再放进自己的效果、空间与工作方式。",
  "home.martello.fieldIndex": "实地测试",
  "home.martello.fieldTitle": "真实 PA 压力下的 Martello。",
  "home.membrana.lead": "Legacy Elements、Modern Modal 与 Pipe Engine——三种合成模型，统一于激励物理、谐振几何与专用音高计算机。",
  "home.membrana.introTitle": "击打、共鸣、塑形。",
  "home.membrana.introLede": "面向膜片、腔体与调谐打击乐的三种模型——各自围绕激励物理、谐振几何与专用音高计算机。",
  "home.membrana.introBody": "Membrana 是物理合成器，不是采样器。Legacy Elements 拿经典膜片气质，Modern Modal 塑谐振腔体，Pipe Engine 做吹奏与击打气柱。击打、共鸣与音高，在一件乐器里完成。",
  "home.membrana.statement": "一件乐器，三套引擎：从复古膜片击打，到模态腔体音色，再到管谐振的气息。",
  "home.membrana.legacyTitle": "复古击打，物理衰减。",
  "home.membrana.legacyBody": "经典击打与吹奏膜片——皮膜张力、腔体敲击、物理乐器的生猛起音，收成可演奏的合成。用模拟时代的态度，为鼓、皮膜与调谐打击乐塑造轮廓、阻尼与衰减。",
  "home.membrana.modalTitle": "塑造模态。调谐腔体。",
  "home.membrana.modalBody": "面向膜片、板材与振动体的模态谐振建模。精细控制泛音、几何与阻尼——从干、紧的击打，到展开的谐波，再到悠长、会唱的衰减。",
  "home.membrana.pipeBody": "吹奏与击打气柱的管物理。风琴、长笛与混合定音打击——气息压力、管径性格、真实气柱的驻波，全部由同一套激励器与音高计算机驱动。",
  "home.membrana.audioTitle": "听 Membrana 的实际示例。",
  "home.membrana.audioLede": "Nobuo Uematsu — <cite>To Zanarkand</cite>，用两个 Membrana 声部与 Galleria 空间效果编排：膜片击打、模态腔体音色，与打磨过的厅堂，融于一曲。",
  "home.galleria.lead": "频谱画廊混响：明亮的公共空间反射，生动的空间运动。",
  "home.galleria.introTitle": "走入画廊。",
  "home.galleria.introLede": "围绕明亮厅堂反射、混合延迟，以及运动驱动的 3D 定位的空间处理。",
  "home.galleria.introBody": "Galleria 是频谱画廊混响——不是死板的房间预设。在同一块面板里处理空间、延迟、轨道与质感：从干爽的公共建筑，到在声场中游走的闪烁尾音。",
  "home.galleria.statement": "Galleria 是一件空间乐器：反射、延迟与运动一起编排——明亮、顺滑、有意落位。",
  "home.galleria.spaceTitle": "公共空间，打磨过的尾音。",
  "home.galleria.spaceBody": "经典与空间混响，独立的早期／晚期平衡、密度、扩散，以及专用闪烁发送。过滤空间、冻结尾音，在不失清晰的前提下推动反射。",
  "home.galleria.motionTitle": "放置声源。推动声场。",
  "home.galleria.motionBody": "声源 X/Y/Z、轨道速率与深度、宽度、多普勒、遮挡与空气感——配实时空间雷达，便于现场定位。延迟与空间共用同一运动逻辑，空间感更连贯。",
  "common.getNotified": "上线提醒",
  "contact.lead": "关于 Martello、授权、安装或订单？发邮件给我们，我们会回复。",
  "contact.includeBody": "请写明平台（Windows 或 Linux）、DAW、已知插件版本，以及问题简述。激活出问题时，请附上结账邮箱。",
  "contact.responseBody": "通常几个工作日内回复。复杂技术问题排查时可能更久一些。",
  "free.lead": "一小套实用工具，贴合日常制作与母带流程。",
  "free.toolBody": "整文件夹转到指定采样率，并导出 MP3——制作、归档、交付都尽量简单。",
  "free.ideasBody": "想在这里看到某款小工具？告诉我们，下一版可以纳入考虑。",
  "dawless.meta.description": "DAWLESS 是面向早期用户的实验项目：不用传统 DAW，也能直接使用乐器与 DSP 的原生环境。",
  "dawless.meta.ogDescription": "面向 MontroneDSP 乐器与 DSP 的原生环境。早期用户实验项目。",
  "dawless.lead": "面向 MontroneDSP 乐器与 DSP 的原生环境。",
  "dawless.statusEarly": "早期用户",
  "dawless.conceptP1": "DAWLESS 是为第一批客户做的实验项目。在原生环境里直接用我们的 DSP 引擎与乐器——不必打开传统 DAW。",
  "dawless.conceptP2": "目标很简单：少干扰、少无限选项，制作与录音的路径更清楚。",
  "dawless.conceptP3": "它不是要取代所有 DAW。而是一个方便开始、作曲、编序、录音与塑音的创作空间——时机到了再往下走。",
  "dawless.workflowIntro": "多数 DAW 一次甩出所有功能。DAWLESS 反过来：路径清楚，关键工具已经就位。",
  "dawless.workflowLi3": "没有通用 DAW 的杂乱界面",
  "dawless.workflowLi4": "创作、编序、录音与塑音的清晰路径",
  "dawless.workflowOutro": "把类似硬件的 DAWless 即时感与专注度，和我们乐器与 DSP 的声音深度结合起来——准备好时，再顺畅导出到传统制作流程。",
  "dawless.nativeP1": "DAWLESS 围绕我们自己的乐器与 DSP——为 MontroneDSP 生态编写，不是从通用宿主移植。",
  "dawless.nativeP2": "引擎是自研：为本环境开发的处理器与乐器，不依赖第三方宿主或现成框架。",
  "dawless.nativeP3": "环境就是引擎。声音设计、合成、处理与编序，跑在和我们插件同一套原生基础上——从一开始就集成，不是事后塞进去。",
  "dawless.exportP1": "你不会被锁在 DAWLESS 里。项目要进传统 DAW，或交给混音／母带工程师时，会提供面向主流 DAW 的会话导出。",
  "dawless.exportP2": "从 DAWLESS 会话进入完整混音与母带，应当直接、轻松。从这里开始，在你的流程需要的地方收尾。",
  "demo.lead": "下载适用于 macOS、Windows 与 Linux 的 Martello 7 天试用。安装前请先看下面的说明。",
  "demo.aboutTitle": "关于试用",
  "demo.aboutBody": "试用版可在 DAW 中检查 Martello 与 MartelloX2：合成鼓、MIDI、稳定性，以及完整版同样的机器冲击感。",
  "demo.aboutLi6": "随时可在商店购买完整版",
  "demo.downloadsIntro": "适用于 macOS、Windows 与 Linux 的试用包。可下载下方手册，或使用各平台链接。安装或使用即表示接受下方<a href=\"#martello-eula\">最终用户许可协议</a>。",
  "demo.eulaMeta": "<strong>Version 1.0.1</strong><br />最后更新：2026年6月14日",
  "privacy.lead": "MontroneDSP 插件以尽量少收集数据为原则。联网只用于许可激活与相关检查、购买、下载、支持与网站运行——不是为了收集你的音乐、会话、预设、MIDI 或音频。",
  "modi.lead": "调谐谐振器乐器的旧概念归档。",
  "modi.title": "这里保留了早期以 Modi 为中心的免费页版本。",
  "modi.body1": "当前免费页转向实用工具与更简洁布局。此归档页仍作早期谐振器乐器概念的参考。",
  "modi.body2": "当时探索的是敲击物理音色、调谐共鸣体、槌击打击乐，以及围绕接触、阻尼与音色展开的紧凑合成。",
}

# fix typo in ja motionBody
ja["home.galleria.motionBody"] = (
  "ソースのX/Y/Z、オービットの速さと深さ、幅、ドップラー、オクルージョン、エア——"
  "ライブの空間レーダー付き。ディレイと空間は同じ動きのロジックに沿い、まとまりのある空間感を保ちます。"
)

for name, fixes in [("ja.json", ja), ("zh-CN.json", zh)]:
    path = base / name
    data = json.loads(path.read_text(encoding="utf-8"))
    for p, v in fixes.items():
        set_path(data, p, v)
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"{name}: {len(fixes)} fixes")

smells = {
  "ja.json": ["フォーカス", "製品ヒーロー", "没入型", "削り出", "彫刻", "手書き", "蒸留", "シンセサイザードラム"],
  "zh-CN.json": ["节奏网格", "专注的鼓", "沉浸式", "雕琢", "手写", "绽放的"],
}
for name, bad in smells.items():
    text = (base / name).read_text(encoding="utf-8")
    hits = [b for b in bad if b in text]
    print(f"{name} leftover: {hits or 'none'}")
